BUCKET_NAME = 'tech-connect-badges'
AVAILABLE_BADGE_PREFIX = 'available'
RANK_META = 'rank'
AWARD_FOR_META = 'award-for'
NAME_META = 'name'
SPECIFIC_AWARD_REASON_META = 'reason-awarded'
AWARDED_PREFIX = 'awarded'
DATE = 'date'
